<a href="https://colab.research.google.com/github/kevin-blasiak-curtin/ISYS2001-Archive/blob/main/Module%2007%20-%20Directing%20Pandas/lab_ticket_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab ticket: sales analysis with pandas

In the worksheet we used pandas to total transactions by category, and we checked its
answers against a loop we understood. Now you do the same kind of work on your own,
with a different dataset and no worked solution to lean on.

This ticket is pass/fail. It is not marked on how polished your code is. It is marked
on whether you can explain what your code does and why you did it that way. Expect to
be asked, out loud, about any line of it.

## The situation

You are looking at a month of sales for an office-supply company. Each row is one
sale. The file `sales_data.csv` has these columns:

- `Date` the day of the sale
- `Product` what was sold
- `Quantity` how many units were sold
- `Unit_Price` the price of one unit
- `Total_Sale` the value of that sale
- `Sales_Rep` who made the sale
- `Region` where it was sold

Your manager wants two things from you: which regions are bringing in the most money,
and how many units of each product are moving. Simple questions. The data will not be
quite as tidy as the questions.

## Before you write anything: look at the data

Open the file and read it as plain text first, the way we did in the worksheet. Do
not load it into pandas yet. Just look.

As you read, ask yourself which columns are numbers and which are text pretending to
be numbers. Some columns have dollar signs. Look carefully at *which* ones, and ask
whether a dollar sign makes sense for what that column is measuring.

In [1]:
# Read sales_data.csv as plain text and look at it.
# What do you notice about the columns? Which ones will need cleaning?

Write one or two sentences here, in plain words, about what you noticed. In
particular: is every column with a dollar sign actually an amount of money? What
would go wrong if you treated all of them the same way?

*(No, every colum with a dollar sign isn't money, unit price and total sale are, quantity isnt. You can't. assume they are. all the same as they are not all currency.)*

## Task 1: total sales by region, highest first

Load the file into a DataFrame, clean whatever needs cleaning so the sale values are
real numbers, and produce the total `Total_Sale` for each `Region`, ordered from
highest to lowest.

Plan it in plain words in the cell below before you write the pandas. If you use an
assistant to help with a line, give it your plan and make sure you can explain what
it hands back.

My plan, in plain words:

![image.png]()(I was really stuck with the upload process as my laptop wouldn't allow the upload, I needed help through Gemini to creat a new file upload section. However Gemini then wrote out the code. I understand reading it, however I still don't understand enough to properly make sense of it)*

In [5]:
# Task 1: total sales by region, highest first.

In [11]:
import pandas as pd

# Load the sales data
df = pd.read_csv('sales_data.csv')

# Display the first few rows to confirm loading and inspect data types
print("Original DataFrame head:")
display(df.head())

# Display initial info to see data types
print("\nOriginal DataFrame info:")
df.info()

Original DataFrame head:

,Date,Product,Quantity,Unit_Price,Total_Sale,Sales_Rep,Region
0,2024-08-01,Business Analytics Software,$2,$2499.00,$4998.00,Sarah Chen,NSW
1,2024-08-01,Office Chair - Ergonomic,$15,$299.50,$4492.50,Michael Wong,VIC
2,2024-08-02,Standing Desk,$8,$599.00,$4792.00,Emma Thompson,QLD
3,2024-08-02,Laptop - Business Grade,$12,$1899.00,$22788.00,David Kumar,NSW
4,2024-08-03,Conference Table,$3,$1250.00,$3750.00,Lisa Park,WA

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        20 non-null     object
 1   Product     20 non-null     object
 2   Quantity    20 non-null     object
 3   Unit_Price  20 non-null     object
 4   Total_Sale  20 non-null     object
 5   Sales_Rep   20 non-null     object
 6   Region      20 non-null     object
dtypes: object(7)
memory usage: 1.2+ KB

### Cleaning `Total_Sale` and `Unit_Price` columns

As observed from the `df.info()` output or by looking at the raw data, the `Total_Sale` and `Unit_Price` columns are likely objects (strings) because of the '$' sign. We need to remove the '$' and convert them to numeric (float) type for calculations.

In [18]:
# Clean 'Total_Sale' column: remove '$' and convert to numeric
df['Total_Sale'] = df['Total_Sale'].astype(str).str.replace('$', '', regex=False).astype(float)

# Also clean 'Unit_Price' for consistency, though not strictly needed for this task
df['Unit_Price'] = df['Unit_Price'].astype(str).str.replace('$', '', regex=False).astype(float)

# Verify the data types after cleaning
print("DataFrame info after cleaning 'Total_Sale' and 'Unit_Price':")
df.info()

DataFrame info after cleaning 'Total_Sale' and 'Unit_Price':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        20 non-null     object
 1   Product     20 non-null     object
 2   Quantity    20 non-null     object
 3   Unit_Price  20 non-null     float64
 4   Total_Sale  20 non-null     float64
 5   Sales_Rep   20 non-null     object
 6   Region      20 non-null     object
dtypes: float64(2), object(5)
memory usage: 1.2+ KB

### Task 1: Total sales by region, highest first

In [13]:
# Calculate total sales by region, highest first
total_sales_by_region = df.groupby('Region')['Total_Sale'].sum().sort_values(ascending=False)

# Display the result
print("Total Sales by Region (highest first):")
display(total_sales_by_region)

Total Sales by Region (highest first):

Region
NSW    $4998.00$22788.00$4799.70$3592.00$4998.75$2994...
QLD                     $4792.00$1895.00$3597.75$1619.55
VIC                     $4492.50$7596.00$7002.00$1995.00
WA                      $3750.00$2598.00$2093.00$1608.25
Name: Total_Sale, dtype: object

### Cleaning `Quantity` column

Based on initial observation, the `Quantity` column also contains '$' signs, making it an `object` type. We need to clean this column by removing the '$' and converting it to an integer for accurate unit counting.

In [19]:
# Clean 'Quantity' column: remove '$' and convert to integer
df['Quantity'] = df['Quantity'].astype(str).str.replace('$', '', regex=False).astype(int)

# Verify the data types after cleaning
print("DataFrame info after cleaning 'Quantity':")
df.info()

DataFrame info after cleaning 'Quantity':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        20 non-null     object
 1   Product     20 non-null     object
 2   Quantity    20 non-null     int64
 3   Unit_Price  20 non-null     float64
 4   Total_Sale  20 non-null     float64
 5   Sales_Rep   20 non-null     object
 6   Region      20 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.2+ KB

In [20]:
print('Re-running cell 9b191573 to clean Quantity column:')
# Clean 'Quantity' column: remove '$' and convert to integer
df['Quantity'] = df['Quantity'].astype(str).str.replace('$', '', regex=False).astype(int)

# Verify the data types after cleaning
print("DataFrame info after cleaning 'Quantity':")
df.info()

Re-running cell 9b191573 to clean Quantity column:
DataFrame info after cleaning 'Quantity':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        20 non-null     object
 1   Product     20 non-null     object
 2   Quantity    20 non-null     int64
 3   Unit_Price  20 non-null     float64
 4   Total_Sale  20 non-null     float64
 5   Sales_Rep   20 non-null     object
 6   Region      20 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.2+ KB

In [21]:
print('\nRe-running cell 20728af0 for Task 2: Total units sold per product:')
# Calculate total units sold per product
units_sold_per_product = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)

# Display the result
print("Total Units Sold per Product (highest first):")
display(units_sold_per_product)

Re-running cell 20728af0 for Task 2: Total units sold per product:
Total Units Sold per Product (highest first):

Product
Desk Lamp - LED                45
Keyboard - Wireless            35
Mouse - Ergonomic              35
Router - Business Grade        25
Monitor - 27 inch              18
Office Chair - Ergonomic       15
Laptop - Business Grade        12
Filing Cabinet                 12
Office Phone System            10
UPS Battery Backup              9
Standing Desk                   8
Printer - Multifunction         8
Air Purifier - Office           7
Projector - 4K Business         6
Shredder - Industrial           5
Coffee Machine - Commercial     4
Whiteboard - Interactive        4
Conference Table                3
Business Analytics Software     2
Security Camera System          2
Name: Quantity, dtype: int64

In [22]:
print('\nRe-running cell 441aa6b2 for Task 1: Total sales by region:')
# Calculate total sales by region, highest first
total_sales_by_region = df.groupby('Region')['Total_Sale'].sum().sort_values(ascending=False)

# Display the result
print("Total Sales by Region (highest first):")
display(total_sales_by_region)

Re-running cell 441aa6b2 for Task 1: Total sales by region:
Total Sales by Region (highest first):

Region
NSW    50902.75
VIC    21085.50
QLD    11904.30
WA     10049.25
Name: Total_Sale, dtype: float64

In [23]:
print('\nRe-running cell 49a3eef4 for Task 3: Sales Rep Revenue:')
# Identify which sales rep brought in the most revenue
sales_rep_revenue = df.groupby('Sales_Rep')['Total_Sale'].sum().sort_values(ascending=False)

# Display the result
print("Sales Revenue by Sales Representative (highest first):")
display(sales_rep_revenue)

Re-running cell 49a3eef4 for Task 3: Sales Rep Revenue:
Sales Revenue by Sales Representative (highest first):

Sales_Rep
David Kumar      32506.50
Michael Wong     21085.50
Sarah Chen       18396.25
Emma Thompson    11904.30
Lisa Park        10049.25
Name: Total_Sale, dtype: float64

## Task 2: units sold per product

Now find how many units of each product were sold in total, using the `Quantity`
column.

This is where looking at the data first pays off. If your numbers come out looking
like money rather than counts of units, stop and work out why before you go on. A
correct answer here should read as sensible unit counts, not dollar amounts.

### Task 2: Total units sold per product

My plan, in plain words:

*(write your plan here before the code)*

In [ ]:
# Task 2: total units sold per product.

In [24]:
# Calculate total units sold per product
units_sold_per_product = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)

# Display the result
print("Total Units Sold per Product (highest first):")
display(units_sold_per_product)

Total Units Sold per Product (highest first):

Product
Desk Lamp - LED                45
Keyboard - Wireless            35
Mouse - Ergonomic              35
Router - Business Grade        25
Monitor - 27 inch              18
Office Chair - Ergonomic       15
Laptop - Business Grade        12
Filing Cabinet                 12
Office Phone System            10
UPS Battery Backup              9
Standing Desk                   8
Printer - Multifunction         8
Air Purifier - Office           7
Projector - 4K Business         6
Shredder - Industrial           5
Coffee Machine - Commercial     4
Whiteboard - Interactive        4
Conference Table                3
Business Analytics Software     2
Security Camera System          2
Name: Quantity, dtype: int64

## Task 3: one question of your own

Pick one more question you could answer from this data and answer it. It does not have
to be complicated. A few honest options:

- Which sales rep brought in the most revenue?
- What is the average sale value in each region?
- Which single product line is worth the most in total sales?

State your question, plan it in words, then write the pandas for it.

In [9]:
import os

# List all files and directories in the current working directory
print(os.listdir('.'))

['.config', 'drive', 'sample_data']

My question, and my plan:

*(Which sales rep brought in the most revenue?)*

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Task 3: your own question.

### Task 3: Which sales rep brought in the most revenue?

In [14]:
# Identify which sales rep brought in the most revenue
sales_rep_revenue = df.groupby('Sales_Rep')['Total_Sale'].sum().sort_values(ascending=False)

# Display the result
print("Sales Revenue by Sales Representative (highest first):")
display(sales_rep_revenue)

Sales Revenue by Sales Representative (highest first):

Sales_Rep
Sarah Chen        $4998.00$4799.70$4998.75$3599.80
Emma Thompson     $4792.00$1895.00$3597.75$1619.55
Michael Wong      $4492.50$7596.00$7002.00$1995.00
Lisa Park         $3750.00$2598.00$2093.00$1608.25
David Kumar      $22788.00$3592.00$2994.00$3132.50
Name: Total_Sale, dtype: object

In [6]:
import os

# List all files and directories in the current working directory
print(os.listdir('.'))

['.config', 'sample_data']

In [15]:
from google.colab import files

print("Please select the 'sales_data.csv' file from your local machine to upload:")
uploaded = files.upload()

# Check if the file was actually uploaded
if 'sales_data.csv' in uploaded:
    print("'sales_data.csv' uploaded successfully!")
else:
    print("Error: 'sales_data.csv' was not found in the uploaded files.")

Please select the 'sales_data.csv' file from your local machine to upload:

KeyboardInterrupt:

In [ ]:
import os

# Verify its presence after upload
print(os.listdir('.'))

## Reflection

Answer these honestly in a sentence or two each. This is the part that is actually
marked.

1. What did looking at the data first tell you that you would have missed if you had
   loaded it straight into pandas?

2. Was there a point where pandas gave you an answer that looked wrong? How did you
   notice, and what did you do?

3. Where in this ticket did you use an assistant, and how did you check that what it
   gave you was right?

*(1. Honesntly,  I would. have missed a lot it looked normal at first but I then noticed the quantity which was off. However I still wanted clarification from Gemini as I didn't want to lead myself down the wrong path.

2.  My whole start to task 1 was incorrect. I was confused how to wrtite it, I needed help with this section and to understand how to start.

3. I used assistants everywhere, I missed last class due to not feeling well and also I feel there isn't enough assistance in the workshops or in class, this is a unit to teach students how to code except not once have I been taugh anything. This is hard enough as it is, more assistnace in class in needed. I didn't mean to uses Gemini to assist me as much as I exepted I just got stuck so much for this ticket. I need to learn to be more spesific with my prompts so Gemini doesn't do the work, but only. assists to push me in the correct direction. )*

## Before you submit

- [x] I looked at the raw data before loading it, and I noted what I saw.
- [x] Task 1 produces total sales by region, highest first.
- [x] Task 2 produces sensible unit counts per product, not dollar amounts.
- [x] Task 3 states a question, a plan, and working code.
- [x] I can explain every line I have written, including any an assistant helped with.
- [x] My reflection answers are honest, including anything that went wrong.